# Generated by Django on 2026-03-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("example", "0002_formulario"),
    ]

    operations = [
        migrations.CreateModel(
            name="UnidadeOrganizacional",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                ("qtd_max_usuarios", models.PositiveIntegerField(default=0)),
                ("qtd_max_coordenadores", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Unidade Organizacional",
                "verbose_name_plural": "Unidades Organizacionais",
            },
        ),
        migrations.CreateModel(
            name="Setor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                (
                    "unidade",
                    models.ForeignKey(
                        on_delete=models.CASCADE,
                        related_name="setores",
                        to="example.unidadeorganizacional",
                    ),
                ),
            ],
            options={
                "verbose_name": "Setor",
                "verbose_name_plural": "Setores",
            },
        ),
        migrations.CreateModel(
            name="Coordenador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                ("matricula", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Coordenador",
                "verbose_name_plural": "Coordenadores",
            },
        ),
        migrations.AddField(
            model_name="coordenador",
            name="setores",
            field=models.ManyToManyField(
                blank=True, related_name="coordenadores", to="example.setor"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="setor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.SET_NULL,
                related_name="usuarios",
                to="example.setor",
            ),
        ),
    ]
