# Generated by Django on 2026-03-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("example", "0003_add_org_setor_coordenador"),
    ]

    operations = [
        migrations.AddField(
            model_name="formulario",
            name="estado",
            field=models.CharField(
                choices=[
                    ("estavel", "Estável"),
                    ("atencao", "Em Atenção"),
                    ("alerta", "Em Alerta"),
                    ("risco", "Em Risco"),
                ],
                default="estavel",
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="formulario",
            name="influencias",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="formulario",
            name="texto_livre",
            field=models.TextField(blank=True, default=""),
        ),
    ]
