# Generated by Django 6.0.3 on 2026-03-09 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0004_update_formulario_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario',
            name='estado',
            field=models.CharField(choices=[('estavel', 'Estável'), ('atencao', 'Em Atenção'), ('alerta', 'Em Alerta'), ('risco', 'Em Risco')], default='estavel', max_length=20),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='texto_livre',
            field=models.TextField(blank=True),
        ),
    ]
