# Generated by Django on 2026-03-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("example", "0005_alter_formulario_estado_alter_formulario_texto_livre"),
    ]

    operations = [
        migrations.AddField(
            model_name="coordenador",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=models.CASCADE,
                related_name="coordenador",
                to="example.user",
            ),
        ),
    ]
